### ISSUE TITLE
Typo in dataset: An incorrect target_api in a code change in prettytable to tabulate migration

### ISSUE THREAD

**Issue by lasendo** [ualberta-smr/PyMigBench#7]
I think the "prettytable__tabulate__educationaltestingservice@skll__f870a659.yaml" file has incorrect "target_api" element for the change "29:39":

```yaml
repo: educationaltestingservice/skll
commit: f870a65904a449103d8f147e9746e548965f27d1
source: prettytable
target: tabulate
commit_url: https://github.com/educationaltestingservice/skll/commit/f870a659
domain: Utility
files:
- path: "skll/experiments.py"
  code_changes:
  - line: "29:39"
    cardinality: not applicable
    source_program_elements: [import]
    target_program_elements: [import]
    properties: []
    source_apis: [prettytable.PrettyTable, prettytable.ALL]
    target_apis: [prettytable.PrettyTable, prettytable.ALL]
  - line: "879-883,900:899-902"
    cardinality: many-to-one
    source_program_elements: [function call, attribute, attribute, function call]
    target_program_elements: [function call]
    properties: [element name change]
    source_apis: [PrettyTable, align, float_format, add_row]
    target_apis: [tabulate]
```

Where "target_apis" for the line:"29:39" should be just "[tabulate]", according to the code in the original commit: https://github.com/educationaltestingservice/skll/commit/f870a659.

This is expected following other cases such as "pep8__pycodestyle__openstack@designate__2c9e9f5f.yaml", where there is an import update from two libraries.
